version: "3.8"

services:
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27017:27017

  postgres-db:
    image: postgres:16.1
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    ports:
      - 5432:5432
